### PR TITLE
Fix 'System.NullReferenceException' when calling Linux services

### LINKED ISSUE #14: 'System.NullReferenceException' occurred in ServiceClientTest.exe
I tried running the ServiceServer and the ServiceClient projects.
The ServiceServer seems to work (I can call the addition service from the ubuntu side).
The ServiceClient however throws an argument null exception at line 66 of the MainWindow.xaml.cs where the responce (resp) seems to be null after the service call.
I investigated a little and I found that in ROS.NET\ROS_Comm\ServiceServerLink.cs line 307 the resp.Serialized becomes null after the call to resp.Deserialize which is the reason why the call at ROS.NET\ROS_Comm\ServiceServerLink.cs line 345 makes the responce to be null.
**UPDATE:** I found out that changing the line ROS.NET\ROS_Comm\ServiceServerLink.cs:345 into
**_resp = (MRes) iresp;//.Deserialize(iresp.Serialized);_**
seems to fix the error.
I will create a pull request.

### PR DESCRIPTION
**Pull request by nickkazepis**
Closes #14

### CODE REVIEW

**Comment by nuclearmistake** [comment]
Just curious, what type was the service that errored?

**Comment by nickkazepis** [comment]
I created a "add_three_numbers" service

>int64 a
>int64 b
>int64 c
>---
>int64 sum

which raised the exception

**Comment by nuclearmistake** [comment]
And sum is set properly when a .net client calls that service advertised by a Linux node?

**Comment by nickkazepis** [comment]
Well, according to my tests it's quite the opposite.
When a service is advertised on the windows side, the linux side can successfully call it (rosservice call).
But when the service is advertised on the linux side, the windows client failed.

**Comment by nuclearmistake** [comment]
Word. Could you double check that this doesn't impact the functionality of ros.net's dynamic reconfigure GUI? If that still functions, I'll merge thus

**Comment by nickkazepis** [comment]
This is a little embarrassing but I haven't gotten to dynamic reconfigure yet so I have no idea how to test if it works or not. I can compile DynamicReconfigureSharp but then I need a dynamically reconfigurable node to test that. Is that right? Would you mind giving me some pointers?

**Comment by nuclearmistake** [comment]
Just run dynamicreconfoguresharp with debugging, or open the dynamic reconfigure solution and run its startup project with F5

**Comment by nickkazepis** [comment]
It compiles and runs already. It shows the GUI  which shows the word "connected" with an empty drop down combo box which has a dash '-'. But I don't know what that is or how it works... :(

**Comment by nuclearmistake** [comment]
Do you have a kinect? Many Openni nodes are dynamic reconfigure enabled... A few other linux ros drivers that come to mind that would show in the drop down list on the reconfigure window would be hokuyo_node, and amcl

**Comment by nickkazepis** [comment]
I have absolutely no idea what you mean (I am completely new to ROS) I will ask a colleague who will hopefully know and I will come back to you. I am trying to create a sample reconfigurable node myself.

**Comment by nuclearmistake** [comment]
Then just pick, /camera/driver in the drop down in the .net reconfigure window, then you should be able to change dynamic reconfigure params (which should change the associated rosparam values, and notify the driver that implements the dynamic reconfigure parameter server instantly)

**Comment by nuclearmistake** [comment]
It's the ros.net equivalent of http://wiki.ros.org/rqt_reconfigure and is
pretty reliant on ros services... Which is why I ask for you to test this
change with it specifically.

**Comment by nickkazepis** [comment]
I still can't manage to create a dynamically reconfigurable node to test this. All the tutorials on ros wiki pages are incomplete... :(

**Comment by nickkazepis** [comment]
Update: I have managed to download compile and run a what is claimed to be dynamicaly reconfigurable node from here: https://github.com/UCSD-E4E/stingray-auv/wiki/Writing-publisher-subscriber-with-dynamic-reconfigure-and-parameter-server-%28C----%29
I started the node on linux.
I run the DynamicReconfigureSharp on windows.
On the Windows side:
------------------------------
If i select the "-" value from the drop down and then select the /talker reconfigurable node, the window shows the configurable options and I am able to change them. However if I try to change my selection to the "-" value, I get a System.ArgumentNullException at:
PageContainer.Children.Add(knownConfigurations[newprefix]); 
where the knownConfigurations["-"] is intentionaly null?
I don't know how this is supposed to work. Can you help me?

**Comment by nuclearmistake** [comment]
Switching TO the "-" might be broken... the dropdown is intended to be used to pick a named node, and the '-' is just no selection.... 

if you rosrun rqt_reconfigure rqt_reconfigure, does the linux gui show configurable parameters? If not, then it might not be the best test case

**Comment by nickkazepis** [comment]
The linux gui shows the configurable parameters and I can change them from the linux GUI.
On the windows side the same GUI is shown but only if I select the "-" option first!
Please mind that:
1. If I select the configurable node /talker as soon as the MainWindow loads, then nothing is shown.
2. If I select the "-" option first and then the /talker node, then the MainWindow loads the same GUI as on the linux side and I can change the parameters BUT
3. If I change from the /talker node (whle the GUI is showing) back to the "-" option an exception is thrown!
So the reconfiguration works, but only if the "-" option is selected first!

**Comment by nuclearmistake** [comment]
ok... so once the mainwindow loads the GUI the same as on the linux side, changing the parameters actually changes them on the linux side? and changing them with rqt_reconfigure on the linux side updates the windows UI?

**Comment by nickkazepis** [comment]
On the linux side, If I change the values through the rqt_reconfigure GUI, the changes are reflected on the windows side at once!

On the windows side, if I change the values directly from the textboxes then yes, the values and the GUI on the Linux side get updated instantaneously! If I use the sliders on the windows side, then the values on the linux side change in "steps" but this has to do with the ros::rate that updates every one second, so the values change with a one second step towards the new value. (sorry, did my best to explain it :)

**Comment by nuclearmistake** [comment]
Seems to function as it has in spite of this commit, which is good. Guess it was double deserializing before this commit.

**Pull request merged**
